# -*- coding: utf-8 -*-
"""llm chatbot rag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14EoLwLVTTmFZy0G3Y51v_zQhTYo4oDsF
"""

! pip install arxiv

pip install Pymupdf

import arxiv

import pandas as pd
from tqdm import tqdm
import re
import os

import fitz

import sys
print(sys.executable)

queries = "cat:cs.AI"   # Healthcare AI related AI research
max_papers = 300
save_pdf_dir = "pdfs"

os.makedirs(save_pdf_dir, exist_ok=True)

client = arxiv.Client()

search = arxiv.Search(
    query=queries,
    max_results=max_papers,
    sort_by=arxiv.SortCriterion.Relevance
)

import fitz
import sys

print(sys.executable)

def extract_text_from_pdf(pdf_path):
    doc = fitz.open(pdf_path)
    text = ""
    for page in doc:
        text += page.get_text()
    doc.close()
    return text

def clean_text(text):
    text = re.split(r"\nReferences\n|\nREFERENCES\n", text)[0]
    text = re.sub(r"\s+", " ", text)
    return text.strip()

client = arxiv.Client()

search = arxiv.Search(
    query=queries,
    max_results=max_papers,
    sort_by=arxiv.SortCriterion.Relevance
)

rows = []

import csv
import json

output_file = "healthcare_ai_papers.jsonl"

for result in tqdm(client.results(search), total=max_papers):

    paper_id = result.get_short_id()
    title = result.title
    topic = ", ".join(result.categories)

    pdf_path = os.path.join(save_pdf_dir, f"{paper_id}.pdf")

    try:
        result.download_pdf(filename=pdf_path)
    except Exception as e:
        print(f"⚠️ Skipping {paper_id}: PDF not available ({e})")
        continue

    raw_text = extract_text_from_pdf(pdf_path)

    if not raw_text or len(raw_text.strip()) < 200:
        print(f"skipping {paper_id}: empty or invalid")
        continue

    clean_content = clean_text(raw_text)

    print(f"{paper_id} : length {len(clean_content)}")

    record = {
        "paper_id": paper_id,
        "title": title,
        "topic": topic,
        "content": clean_content
    }

    with open(output_file, "a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")

print("Saved healthcare_ai_papers.jsonl")

queries = "cat:q-bio.QM"   # Quantitative biology / medical modeling
max_papers = 300

save_pdf_dir = "pdfs"
os.makedirs(save_pdf_dir, exist_ok=True)

output_file = "healthcare_biology_papers.jsonl"

import pandas as pd

df = pd.read_json("healthcare_ai_papers.jsonl", lines=True)
df

df = df.dropna(subset=["content"])
df = df[df["content"].str.strip().str.len() > 1000]

def fix_encoding(text):
    return (
        text
        .replace("\x00", "")
        .replace("¿", "")
        .replace("�", "")
    )

df["content"] = df["content"].apply(fix_encoding)
df["title"] = df["title"].apply(fix_encoding)

df["content"] = df["content"].apply(
    lambda x: "".join(ch for ch in x if ch.isprintable())
)

df["content"] = df["content"].str.replace(
    r"arXiv:\d+\.\d+v\d+\s+\[.*?\]\s+\d+\s+\w+\s+\d+",
    "",
    regex=True
)

df = df.drop_duplicates(subset=["paper_id"])

df.to_json(
    "healthcare_ai_clean.jsonl",
    orient="records",
    lines=True,
    force_ascii=False
)

input_files = [
    "healthcare_ai_clean.jsonl",
]

output_file = "all_healthcare_papers_combined.jsonl"

seen_ids = set()
total_written = 0

with open(output_file, "w", encoding="utf-8") as out:
    for file in input_files:
        with open(file, "r", encoding="utf-8") as f:
            for line in f:

                try:
                    record = json.loads(line)
                except:
                    continue

                pid = record.get("paper_id")

                if not pid or pid in seen_ids:
                    continue

                seen_ids.add(pid)

                out.write(json.dumps(record, ensure_ascii=False) + "\n")
                total_written += 1

print("Total combined records:", total_written)

import pandas as pd

df = pd.read_json("all_healthcare_papers_combined.jsonl", lines=True)

print(len(df))
print(df["paper_id"].nunique())

import json

total_lines = 0
valid_json = 0
invalid_lines = []

with open("all_healthcare_papers_combined.jsonl", "r", encoding="utf-8") as f:

    for i, line in enumerate(f, 1):
        total_lines += 1

        try:
            json.loads(line)
            valid_json += 1
        except Exception:
            invalid_lines.append(i)

print("Total lines in file:", total_lines)
print("Valid JSON lines:", valid_json)
print("Invalid JSON lines:", len(invalid_lines))

rag_data = []

with open("all_healthcare_papers_combined.jsonl", "r", encoding="utf-8") as f:

    for line_no, line in enumerate(f, start=1):

        line = line.strip()
        if not line:
            continue

        try:
            item = json.loads(line)
        except json.JSONDecodeError as e:
            print(f"❌ Error parsing line {line_no}: {e}")
            continue

        rag_data.append({
            "topic": item.get("topic"),
            "content": f"Title: {item.get('title', '')}\n\n{item.get('content', '')}"
        })

print(f"Parsed {len(rag_data)} records successfully")

with open("healthcare_papers_for_rag.json", "w", encoding="utf-8") as f:
    json.dump(rag_data, f, ensure_ascii=False, indent=2)

print("healthcare_papers_for_rag.json created")

pip install langchain langchain-community langchain-text-splitters faiss-cpu sentence-transformers groq jq

from google.colab import drive
drive.mount('/content/drive')

import json
from langchain_core.documents import Document

file_path = "/content/drive/MyDrive/healthcare_papers/healthcare_papers_for_rag.json"

with open(file_path, "r", encoding="utf-8") as f:
    data = json.load(f)

documents = []

for item in data:
    documents.append(
        Document(page_content=item["content"], metadata={"topic": item["topic"]})
    )

print("Documents loaded:", len(documents))

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=300,
    chunk_overlap=100
)

docs = text_splitter.split_documents(documents)

print("Total chunks:", len(docs))

from langchain_community.embeddings import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

from langchain_community.vectorstores import FAISS

vectorstore = FAISS.from_documents(docs, embeddings)

retriever = vectorstore.as_retriever(search_kwargs={"k": 3})

print("Vector database created")

query = "How is AI used in healthcare diagnosis?"

retrieved_docs  = retriever.invoke(query)

context = "\n\n".join([doc.page_content for doc in retrieved_docs])

print(context[:1000])

from groq import Groq

client = Groq(api_key="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")

prompt = f"""
Answer the question using the research papers below.

Context:
{context}

Question:
{query}
"""

response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {"role": "user", "content": prompt}
    ],
    temperature=0.3,
    max_tokens=512
)

print(response.choices[0].message.content)

